### ISSUE TITLE
ERROR in TypeError: Converting circular structure to JSON + Invariant Violation

### ISSUE THREAD

**Issue by connor11528** [jxnblk/react-static-site-boilerplate#9]
Steps to reproduce

```
$ git clone <this_repo>
$ npm i
$ npm start
```

Interestingly everything builds but there is an error in the console:

```
ERROR in TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at safeStringify (bundle.js:23632:16)
    at React.createClass.render (bundle.js:23608:16)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (bundle.js:11791:35)
    at ReactCompositeComponentMixin._renderValidatedComponent (bundle.js:11818:15)
    at wrapper [as _renderValidatedComponent] (bundle.js:3524:22)
    at ReactCompositeComponentMixin.mountComponent (bundle.js:11239:31)
    at wrapper [as mountComponent] (bundle.js:3524:22)
    at Object.ReactReconciler.mountComponent (bundle.js:3599:36)
    at ReactCompositeComponentMixin.mountComponent (bundle.js:11249:35)
```

Then there is another error in the browser:

```
Uncaught Error: Invariant Violation: You're trying to render a component to the document using server rendering but the checksum was invalid. This usually means you rendered a different component type or props on the client from the one on the server, or your render() methods are impure. React cannot handle this case due to cross-browser quirks by rendering at the document root. You should look for environment dependent code in your components and ensure the props are the same client and server side:
 (client) =".1w1vfuoi9ds.0.1">body{margin:0}img{ma
 (server) =".1w1vfuoi9ds.0.1">.black,.dark-gray,bo
```

**Comment by alexslade** [comment]
@cleechtech Very new to react + this repo (and Node in general), so just sharing some basic working in case it's helpful. Sorry if it's super n00b.

The initialProps variable is used in the HTML snippet to create a script tag containing some JSON. Wtf it does there - I have no idea :). The safeStringify method converts an object into JSON, so you've ended up inserting a raw object into the HTML instead of JSON (hence the Unexpected token o error).

safeStringify is failing is because the props object contains circular references, which blows up the invocation of JSON.stringify inside it.

If you remove `webpackStats` from props, it continues without issue (except a warning to not modify props!). 

I.e. 

```
  render: function () {
    this.props.webpackStats = undefined
    var initialProps = {
      __html: safeStringify(this.props)
    }
```

@jxnblk Could you enlighten us at to what `webpackStats` is used for and where those circular refs are coming from?

**Comment by connor11528** [comment]
Ok thank you for this. @jxnblk any thoughts?

**Comment by ntdb** [comment]
+1

**Comment by jxnblk** [comment]
I _think_ that `webpackStats` is something webpack-dev-server uses internally. This wasn't an issue when I first put this boilerplate together, but I do plan on giving it an update soon.

**Comment by jxnblk** [comment]
I'm guessing this is the culprit: https://github.com/markdalgleish/static-site-generator-webpack-plugin/blob/master/CHANGELOG.md#120---2015-10-06

**Comment by connor11528** [comment]
Totally works now. Thank you for the PR fix
